### ISSUE TITLE
Frontend, Backend, Mobile e Games - Developer

### ISSUE THREAD

**Issue by TaisTeodoro** [minasdev/newsletter#18]
Vagas para desenvolvedor Frontend, Backend, Mobile e Games na empresa Studio Sol.

Fundada em Belo Horizonte, em 2000, por Sam Vignoli e Gabriel Fernandes, a Studio Sol é proprietária do Cifra Club, Palco MP3 e Letras.mus.br. 
Também faz o Guitar Battle, Fórum Cifra Club e Forme Sua Banda.

Somos a empresa brasileira líder em download de aplicativos e Top Developer na Google Play.

Inscrição no link: https://www.studiosol.com.br/desenvolvedores/

**Comment by obetomuniz** [comment]
Oi @TaisTeodoro, fique a vontade de postar novas vagas no novo repositório [minasdev/vagas](https://github.com/minasdev/vagas). 👍
