### ISSUE TITLE
10 dicas para se tornar um melhor programador em Swift

### ISSUE THREAD

**Issue by 3jacksonsmith** [minasdev/newsletter#9]
https://vikingscode.com/swift/10-dicas-para-se-tornar-um-melhor-programador-em-swift/

**Comment by obetomuniz** [comment]
Por favor, adicione este link como comentário na issue [github.com/minasdev/newsletter/issues/7](https://github.com/minasdev/newsletter/issues/7) utilizando o formato proposto por ela
